### ISSUE TITLE
Criar esqueleto do Storage

### ISSUE THREAD

**Issue by casimiroarruda** [PHPSP/liga-solidaria-storage#1]
**Como** Desenvolvedor
**Gostaria de** ter uma base de projeto
**Para** desenvolve-lo de forma organizada

**Comment by filhodanuvem** [comment]
Algo ficou decidido desde que eu saí da sala, sobre componentes que usaremos?

**Comment by hussani** [comment]
@cloudson ficou decidido que usaremos os componentes do Respect.
Por enquanto os componentes serão Config, Relational, Rest e Validation.

**Comment by filhodanuvem** [comment]
Certo!

**Comment by augustohp** [comment]
Po, to gostando dessa história ae!

**Comment by casimiroarruda** [comment]
Você já viu o wiki do projeto hoje? https://github.com/PHPSP/liga-solidaria-storage/wiki ;)

**Comment by filhodanuvem** [comment]
Boa @duodraco , esqueci da wiki :+1:

**Comment by casimiroarruda** [comment]
Tem mais novidade ;) https://waffle.io/PHPSP/liga-solidaria-storage

**Comment by aleborba** [comment]
:+1:

**Comment by hussani** [comment]
Pessoal,

segue a estrutura básica no PR #12

**Comment by aleborba** [comment]
Como estão as coisas aqui @hussani? Já passou a bola ou tem algo mais?

**Comment by hussani** [comment]
Só vai faltar ignorar o config/config.ini. 
Vou fazer isso assim que chegar em casa e aí está tarefa estará pronta.

**Comment by hussani** [comment]
Galera, o skeleton já está no branch develop.
Vou fechar a issue. Se surgir mais alguma coisa referente ao skeleton podem abrir de novo.

**Comment by aleborba** [comment]
:+1:
