### ISSUE TITLE
Melhorar documentação para permitir contribuições externas

### ISSUE THREAD

**Issue by augustohp** [PHPSP/liga-solidaria-storage#19]
Eu, por exemplo estou com bastante dificuldade em conseguir contribuir com alguma coisa. Até em qualquer discussão fica difícil, minhas principais dúvidas são:
- Qual o objetivo do projeto?
- O que é A Liga Solidária? (Não seria relevante se o objetivo fosse claro)
- Existem projetos relacionados? (Que serão criados depois)
- Claramente existiu muita discussão em cima do projeto já, mas aparentemente essas decisões não estão expostas em lugar nenhum.

**Comment by aleborba** [comment]
:+1: 

Esta correto, vou providenciar isso hoje

**Comment by rogeriopradoj** [comment]
+1

**Comment by hussani** [comment]
Algo por aqui PO @aleborba? =)

**Comment by pauloelr** [comment]
@aleborba Eu editei o arquivo Como Contribuir da Wiki
Depois vocês dão uma olhada lá para ver se está tudo certo.
Assim quem tiver mais dúvidas sobre como contribuir já tem por onde começar.

**Comment by pauloelr** [comment]
Eu também achei essa página:
https://github.com/PHPSP/liga-solidaria-storage/wiki/Guia-de-contribui%C3%A7%C3%A3o
Que parece ser um Guia mais antigo de contribuição, eu inclui algumas das informa na nova página que eu criei, então acho que essa página antiga já pode ser deletada, certo? Não vejo sentido para ter duas páginas com quase o mesmo conteúdo

**Comment by aleborba** [comment]
:+1:

**Comment by rogeriopradoj** [comment]
@pauloelr, apaguei a página antiga.

Fechando essa issue.

@augustohp, diz depois se acredita ser o suficiente, se não for abrimos de novo, ok?

Falou!
