### ISSUE TITLE
View Handler

### ISSUE THREAD

**Issue by hussani** [PHPSP/liga-solidaria-storage#20]
Galera,

acham necessário usar algum componente para manipulação de views?
Gostaria de usar o Twig, mas preciso saber o que vocês acham disso.

Ultimamente os retornos para o usuário estão sendo feitos direto nos controllers, e em breve isso se tornará um problema.

O que vocês acham?
Tem alguma sugestão?

Abraço!

**Comment by rogeriopradoj** [comment]
Última vez que falei com o @alganet e o @wesleyvicthor eles falaram que estão em um projeto que é tudo Respect exceto a engine de templates (que no caso deles é Twig).

:+1: para Twig.

**Comment by filhodanuvem** [comment]
:heart: para Twig

**Comment by williamespindola** [comment]
Manda bala com o Twig, todos sabem trabalhar com ele acredito. De repente se rodar algum trampo com javascript eu recomendo o [Hogan](http://twitter.github.io/hogan.js/)

**Comment by hussani** [comment]
Coloquei o Twig no projeto
