### ISSUE TITLE
Layout Liga Solidária

### ISSUE THREAD

**Issue by aleborba** [PHPSP/liga-solidaria-storage#37]
**Como** usuário do storage
**Gostaria de** ver a identidade visual da liga solidária
**Para** que eu me sentir mais a vontade sabendo que é um sistema da ONG

**Comment by pauloelr** [comment]
Se alguém mandar pra mim o logo dos caras eu assumo essa issue aqui.
Até por que estou que estou querendo fazer uns testes com a versão 3 do bootstrap ai já junta dois coelhos.
Mas eu preciso do logo pra ter uma ideia de que cores utilizar, da identidade visual e tal.

Como vou fazer:
Primeiro vou fazer um png com a ideia inicial e publicar aqui.
Se estiver tudo certo eu crio o Front-end

Blz?

**Comment by aleborba** [comment]
Show de bola @pauloelr!

A identidade da liga atualmente é esta aqui ó: http://www.ligasolidaria.org.br/

**Comment by pauloelr** [comment]
Maravilha

Já vou começar aqui, assim que tiver alguma coisa posto aqui.

**Comment by rogeriopradoj** [comment]
:+1: para o PR #38.

**Comment by pauloelr** [comment]
Fechando esse aqui já que o PR já foi mesclado
Se ainda precisar alterar alguma coisa no layout avisem que eu abro de novo. :smile:
