### ISSUE TITLE
Upload de Arquivos

### ISSUE THREAD

**Issue by aleborba** [PHPSP/liga-solidaria-storage#8]
**Como** administrador do Storage
**Gostaria que** fazer upload de arquivos
**Para** que os usuários consigam baixá-los

**Comment by ericktedeschi** [comment]
em se falando de envio e arquivos um ponto importante em ser pensado é a integridade do mesmo e também os tipos de arquivos aceitos. Para criar uma cadeia de validação.

**Comment by williancarminato** [comment]
@ericktedeschi de fato isso é importante porém segundo o @aleborba, nosso PO, o cliente não necessita de validação e portanto nesse primeiro Sprint não teremos isso.

**Comment by aleborba** [comment]
Mas com certeza isso vai entrar em uma história, logo menos.

**Comment by williancarminato** [comment]
Concordo :smile:

**Comment by aleborba** [comment]
Novidades por aqui @williancarminato?

**Comment by williancarminato** [comment]
@aleborba comecei exatamente agora cara, amanhã atualizo você e o repositório

**Comment by aleborba** [comment]
:+1:

**Comment by williancarminato** [comment]
Fala galera, fiz o upload de arquivos, conforme combinado o básico, sem banco de dados.

Tá nesse branch aqui [feature-file-upload](https://github.com/PHPSP/liga-solidaria-storage/tree/feature-file-upload).

Quem puder me ajudar com os testes pois eles ainda não estão 100%.

Outra coisa, seria uma boa alguém fazer um template padrão para todos usarem, com html e css do bootstrap pra não ficar todo mundo diferente.

É isso, valeu!

**Comment by aleborba** [comment]
:+1:

**Comment by aleborba** [comment]
O @williamespindola estava trabalhando em um front end.

**Comment by hussani** [comment]
Galera,
o upload de arquivos já está funcional.
Vamos acertando os testes, mas a funcionalidade está ok.

Vou fechar a issue.
