### ISSUE TITLE
Lista de Arquivos

### ISSUE THREAD

**Issue by aleborba** [PHPSP/liga-solidaria-storage#9]
**Como** usuário do Storage
**Gostaria que** fosse possível visualizar todos os arquivos
**Para** poder escolher qual eu preciso

**Comment by aleborba** [comment]
Caro amigo @hussani, o dono de todas as issues! :P Novidades aqui?

**Comment by hussani** [comment]
@aleborba por aqui ainda nada.
Começo amanha e já mostro algo para vocês. ;)

**Comment by aleborba** [comment]
:+1:

**Comment by augustohp** [comment]
Eu não sei direito do que se trata, mas se a intenção for manipular arquivos mesmo; que tal consumir o [SabreDAV](https://github.com/fruux/sabre-dav)?

**Comment by hussani** [comment]
@augustohp nossa cara, não conhecia esse framework.
Ele é animal nessa parte de manipular arquivos e pastas.

Por enquanto não sei se ele cabe no projeto, mas quando soubermos mais sobre os requisitos da aplicação vou ficar bem interessado em utilizar ele na camada de mapeamento dos arquivos.

**Comment by rogeriopradoj** [comment]
+1

**Comment by aleborba** [comment]
Novidades por aqui @hussani?

**Comment by hussani** [comment]
@aleborba mandei a listagem de arquivos.
Agora só estou o dowload deles. Este fds eu entrego esta ultima parte

**Comment by williamespindola** [comment]
Posso mesclar esta listagem com o front que havia feito?

**Comment by hussani** [comment]
@williamespindola pode sim.
Vai ajudar bastante já.

**Comment by aleborba** [comment]
E ai pessoal, vamos conseguir fazer a primeira entrega amanha no Pub?!

**Comment by rogeriopradoj** [comment]
Oi @aleborba, amanhã no Pub tem live coding.

**Comment by hussani** [comment]
Download de arquivos também ok!

Vou fechar a issue.
